name: Validate Lint and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test
